#Tiltfile

docker_compose('docker-compose.yml')

# backend = {
#     "newsletter-microservice": "http://localhost:420/",
#     "users-microservice": "http://localhost:1017/",
#     "deno-microservice": "http://localhost:4200/"
# }

# frontend = {
#     "ui-starter-app": "http://localhost:3000/",
#     "xsj-consulting-app": "http://localhost:4269/",
#     "xsj-reusable-components-library": "http://localhost:6006/"
# }

backend_services = {
    "postgres": "http://localhost:5432/",
    "redis": "http://localhost:6379/",
    "elasticsearch": "http://localhost:9200/",
    "memcached": "http://localhost:11211/",
    "mongodb": "http://localhost:27017/",
    "cassandra": "http://localhost:9042/",
    # "zookeeper": "http://localhost:2181/",
    # "kafka": "http://localhost:9092/"
}

# Function to register additional services
def register_backend_services():
    for service in backend_services:
        dc_resource("{}".format(service), labels=["backend_service"])

register_backend_services()

# def register_backend():
#     for service in backend:
#         dc_resource("{}".format(service), labels=["back_end"])

# register_backend()

# def register_frontend():
#     for service in frontend:
#         dc_resource("{}".format(service), labels=["front_end"])

# register_frontend()